name: API Sentinel CI

on:
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run "collections/API Sentinel - Layer7.postman_collection.json" \
            -e "collections/API Sentinel - Layer7.postman_environment.json" \
            --timeout-request 5000 \
            --timeout 60000 \
            -r cli,htmlextra \
            --reporter-htmlextra-export reports/report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: Newman-Report
          path: reports/report.html